services:
  apache:
    image: 'httpd:latest'
    container_name: apache
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./app:/usr/local/apache2/htdocs 

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: application
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3306